[tool.poetry]
name = "olho-de-deus"
version = "0.1.0"
description = "Sistema de monitoramento inteligente para câmeras públicas"
authors = ["Douglas Scarello <douglasdsr@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
opencv-python = "^4.13.0.92"
yt-dlp = "^2026.2.21"
requests = "^2.32.5"
beautifulsoup4 = "^4.14.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
